language: go
go:
  - 1.5
  - tip

install:
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race
